AWSTemplateFormatVersion: 2010-09-09
Description:  This template creates EC2 Instance inside a public A subnet of Bison Network.
Parameters:
    InstanceType:
        Type: String
        Description: EC2 instance type
        Default: t2.micro
        AllowedValues:
            - t2.micro
    AMI:
        Type: AWS::EC2::Image::Id
        Default: ami-0474863011a7d1541
        Description: The Linux AMI to use.
    NetworkName:
        Type: String
        Description: Network name instances to be attached to
        Default: Bison
Resources:
    PublicInstance1:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType: !Ref InstanceType
            ImageId: !Ref AMI
            Tags: 
                - Key: Name
                  Value: !Sub ${NetworkName}PublicInstanceA
            SubnetId: 
                Fn::ImportValue: 
                    !Sub ${NetworkName}PublicSubnetA
    PublicInstance2:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType: !Ref InstanceType
            ImageId: !Ref AMI
            Tags: 
                - Key: Name
                  Value: !Sub ${NetworkName}PublicInstanceB
            SubnetId: 
                Fn::ImportValue: 
                    !Sub ${NetworkName}PublicSubnetB
    BisonPrivateInstance1:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType: !Ref InstanceType
            ImageId: !Ref AMI
            Tags: 
                - Key: Name
                  Value: !Sub ${NetworkName}PrivateInstanceA
            SubnetId: 
                Fn::ImportValue: 
                    !Sub ${NetworkName}PrivateSubnetA
    BisonPrivateInstance2:
        Type: 'AWS::EC2::Instance'
        Properties:
            InstanceType: !Ref InstanceType
            ImageId: !Ref AMI
            Tags: 
                - Key: Name
                  Value: !Sub ${NetworkName}PrivateInstanceB
            SubnetId: 
                Fn::ImportValue: 
                    !Sub ${NetworkName}PrivateSubnetB
    
  